/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-04-24 11:32:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class ListaDeCompra_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Video 237-238: Lista de compra</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<form name=\"Formulario_Compra\" action=\"ListaDeCompra.jsp\"> \r\n");
      out.write("	  <p>Artículos a comprar:</p>\r\n");
      out.write("	  <p>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"articulos\" value=\"agua \" >Agua </label>\r\n");
      out.write("	    <br>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"articulos\" value=\"leche\" >Leche </label>\r\n");
      out.write("	    <br>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"articulos\" value=\"pan\" >Pan </label>\r\n");
      out.write("	    <br>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"articulos\" value=\"mazanas\" >Manzanas </label>\r\n");
      out.write("	    <br>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"articulos\" value=\"carne\" >Carne </label>\r\n");
      out.write("	    <br>\r\n");
      out.write("	    <label><input type=\"checkbox\" name=\"articulos\" value=\"pescado\" >Pescado </label>\r\n");
      out.write("	  </p>\r\n");
      out.write("	  <p>\r\n");
      out.write("	    <input type=\"submit\" name=\"button\" id=\"button\" value=\"Enviar\">\r\n");
      out.write("	    <br>\r\n");
      out.write("	  </p>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<h2>Carro de la compra</h2>\r\n");
      out.write("	<ul>\r\n");
      out.write("	");

		//Guarda los elementos elegidos en el carro de la compra.
		List<String> ListaElementos = (List<String>) session.getAttribute("misElementos");
		if(ListaElementos==null){
			ListaElementos = new ArrayList<String>();
			session.setAttribute("misElementos", ListaElementos);
		}
		
		//Rescata los datos del formulario, cuando el usuario pulsa el botón de enviar. 
		String[]elementos = request.getParameterValues("articulos");
		if(elementos!=null){
			for(String elemTemp : elementos){
				ListaElementos.add(elemTemp);
			}
		}
		
		//imprimimos el arraylist
		for(String elemTemp : ListaElementos){
			out.println("<li>" + elemTemp + "</li>");
		}
	
      out.write("\r\n");
      out.write("	</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
